name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Fetch tags
        run: git fetch --tags

      - name: Read current version
        run: |
          CURRENT=$(dotnet msbuild -nologo -v:q -getProperty:Version)

          if [ -z "$CURRENT" ]; then
            echo "Failed to read version"
            exit 1
          fi

          echo "CURRENT=$CURRENT" >> $GITHUB_ENV
          echo "Current version: $CURRENT"

      - name: Compute next version
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.CURRENT }}"

          NEXT_PATCH=$((PATCH+1))
          NEXT="$MAJOR.$MINOR.$NEXT_PATCH"

          echo "NEXT=$NEXT" >> $GITHUB_ENV
          echo "Next version: $NEXT"

      - name: Update Directory.Build.props
        run: |
          sed -i -E "s#<Version>.*</Version>#<Version>${{ env.NEXT }}</Version>#g" Directory.Build.props

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add Directory.Build.props
          git commit -m "chore: bump version to ${{ env.NEXT }}"
          git push origin main

      - name: Create release tag
        run: |
          if git rev-parse "v${{ env.NEXT }}" >/dev/null 2>&1; then
            echo "Tag already exists!"
            exit 1
          fi

          git tag v${{ env.NEXT }}
          git push origin v${{ env.NEXT }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Pack
        run: |
          dotnet pack \
            -c Release \
            -p:PackageVersion=${{ env.NEXT }} \
            --no-build \
            -o ./nupkg

      - name: Publish to NuGet
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
