name: Release

on:
  workflow_dispatch:
    inputs:
      rc_tag:
        description: "RC tag to promote (ex: v0.0.9-rc.5)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --tags

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Store RC tag
        run: |
          TAG="${{ github.event.inputs.rc_tag }}"

          if [[ ! $TAG =~ ^v([0-9]+\.[0-9]+\.[0-9]+)-rc\.[0-9]+$ ]]; then
            echo "Invalid RC tag format"
            exit 1
          fi

          VERSION="${BASH_REMATCH[1]}"

          echo "RC_TAG=$TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          echo "RC tag: $TAG"
          echo "Release version: $VERSION"

      - name: Ensure release tag does not exist
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Release tag already exists!"
            exit 1
          fi

      - run: dotnet restore

      - run: dotnet build -c Release --no-restore

      - name: Pack
        run: |
          dotnet pack \
            -c Release \
            -p:PackageVersion=${{ env.VERSION }} \
            --no-build \
            -o ./nupkg

      - name: Create release tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }} --force

      - name: Publish to NuGet
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
